### ISSUE TITLE
[Feature Request] Quick shortcut to rollback 10 secs

### ISSUE THREAD

**Issue by warezit** [caeleel/twitch-dvr#4]
Love this extension! Working great with Brave browser!

Just curious, is it possible to add a feature to quickly rollback 10 secs?

![image](https://user-images.githubusercontent.com/8278779/91903424-d905a080-ec68-11ea-93f9-797a4f9d0b91.png)

That's all! 😄

**Comment by caeleel** [comment]
Hitting left arrow should do this! Note that if you're live, it will roll back 20s because there's a dead zone between live and VOD where the VOD hasn't been saved yet.

**Comment by warezit** [comment]
> Hitting left arrow should do this! Note that if you're live, it will roll back 20s because there's a dead zone between live and VOD where the VOD hasn't been saved yet.

That's awesome! Thanks for the reply, and the tip! 👍 😊
