### ISSUE TITLE
Clipping is broken + suggestions

### ISSUE THREAD

**Issue by TBloop** [caeleel/twitch-dvr#8]
Hi there,

Your extension is much needed and I cant believe twitch hasn't implemented it yet.

Clipping is currently broken, no matter which channel im on and whether an ad is playing or not it gives the error message. Is this fixable? 

Also is it possible to add a theater mode button? I know you can use the shortcut but its a lot nicer to have the button.

Thank you!

edit: Also the clipping button goes away when you rewind. Is it possible to still have it if you are not live? Very often I will want to clip something that happened previously - if this extension can't do it then I'd have to just go to the VOD anyways which defeats the point of it.

**Comment by caeleel** [comment]
I fixed clipping in VOD mode in the latest release (should be coming out soon).

hm, for deleted and hidden vods, I don't think that the video urls are deterministic so I don't think I can get the video URL without calling twitch's api (which doesn't return deleted VODs). I could definitely be wrong though.

As for compatibility with video adblock for twitch, as an ex-twitch employee I unfortunately don't feel super comfortable explicitly supporting compatibility with that extension, I'm sorry :(.
